disable aluvm log feature
RGB-WG/rgb-schemata pull request #34
Opened 2024-03-12 12:47 UTC by nicbus

This PR disables `aluvm`'s `log` feature (ref. https://github.com/AluVM/rust-aluvm/issues/101) to prevent verbose messages being printed.

2024-03-13 09:37 UTC, nicbus commented
I think those messages should be removed as they should not appear during normal operation and they make reading logs from applications using RGB harder.

In other words, I think `aluvm`'s `log` feature should be enabled when developing but not in `master`.

2024-03-14 15:14 UTC, dr-orlovsky commented
Before the release RGB shouldn't be used for real assets. So is it that these logs make your debugging harder?

2024-03-18 09:00 UTC, nicbus commented
This is not being used for real assets, it's used to test the upcoming v0.11 is working as expected and yes, these logs make it harder to to review and debug the logs from the higher-level application.

I can live with this, so if they're so important to you at the moment, let's keep them. Please leave this open as a reminder so we can drop the logs when they won't be as useful to you as they are now.

2024-03-19 07:26 UTC, dr-orlovsky commented on Cargo.toml
> +aluvm = { version = "0.11.0-beta.4" }
```suggestion
aluvm = "0.11.0-beta.4"
```

2024-03-19 10:32 UTC, nicbus commented
> Can we remove it in the dependencies and add as a feature at the crate level?

Even better, done.

2024-03-19 10:36 UTC, nicbus commented on Cargo.toml
> +aluvm = { version = "0.11.0-beta.4" }
done

2024-03-19 10:54 UTC, dr-orlovsky requested changes
Sorry on more thing is missed

2024-03-19 10:54 UTC, dr-orlovsky commented on Cargo.toml
>  all = []
all = ["log"]

2024-03-19 11:53 UTC, nicbus commented on Cargo.toml
>  all = []
done

2024-03-19 15:08 UTC, dr-orlovsky approved these changes
ACK https://github.com/BP-WG/bp-esplora-client.git

2024-03-19 15:09 UTC, merged